# Generated by Django 3.2.3 on 2021-05-31 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('status', models.CharField(choices=[('fila', 'Na Fila'), ('andamento', 'Em andamento'), ('completa', 'Completa')], default='fila', max_length=9, verbose_name='Status')),
                ('urgency', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', max_length=5, verbose_name='Urgencia')),
                ('rgb_hex_code', models.CharField(max_length=7, null=True, verbose_name='Codigo RGB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planner.planner')),
            ],
        ),
    ]
